/* tslint:disable */
/* eslint-disable */
/**
 * Hey Pharamcist API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { DeleteFileDto } from '../models';
import { DeleteManyFilesDto } from '../models';
/**
 * FileProccesorApi - axios parameter creator
 * @export
 */
export const FileProccesorApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Delete file from S3
         * @param {DeleteFileDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteFileFromS3: async (body: DeleteFileDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling deleteFileFromS3.');
            }
            const localVarPath = `/file-proccesor/delete`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || (localVarRequestOptions.headers ||= {})['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete many files from S3
         * @param {DeleteManyFilesDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteManyFilesFromS3: async (body: DeleteManyFilesDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling deleteManyFilesFromS3.');
            }
            const localVarPath = `/file-proccesor/delete-many`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || (localVarRequestOptions.headers ||= {})['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Upload file to S3
         * @param {Blob} file 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadFileToS3Form: async (file: Blob, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'file' is not null or undefined
            if (file === null || file === undefined) {
                throw new RequiredError('file','Required parameter file was null or undefined when calling uploadFileToS3Form.');
            }
            const localVarPath = `/file-proccesor/upload`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new FormData();


            if (file !== undefined) { 
                localVarFormParams.append('file', file as any);
            }

            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FileProccesorApi - functional programming interface
 * @export
 */
export const FileProccesorApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Delete file from S3
         * @param {DeleteFileDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteFileFromS3(body: DeleteFileDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<boolean>>> {
            const localVarAxiosArgs = await FileProccesorApiAxiosParamCreator(configuration).deleteFileFromS3(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Delete many files from S3
         * @param {DeleteManyFilesDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteManyFilesFromS3(body: DeleteManyFilesDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<boolean>>> {
            const localVarAxiosArgs = await FileProccesorApiAxiosParamCreator(configuration).deleteManyFilesFromS3(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Upload file to S3
         * @param {Blob} file 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async uploadFileToS3Form(file: Blob, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<string>>> {
            const localVarAxiosArgs = await FileProccesorApiAxiosParamCreator(configuration).uploadFileToS3Form(file, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * FileProccesorApi - factory interface
 * @export
 */
export const FileProccesorApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Delete file from S3
         * @param {DeleteFileDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteFileFromS3(body: DeleteFileDto, options?: AxiosRequestConfig): Promise<AxiosResponse<boolean>> {
            return FileProccesorApiFp(configuration).deleteFileFromS3(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete many files from S3
         * @param {DeleteManyFilesDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteManyFilesFromS3(body: DeleteManyFilesDto, options?: AxiosRequestConfig): Promise<AxiosResponse<boolean>> {
            return FileProccesorApiFp(configuration).deleteManyFilesFromS3(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Upload file to S3
         * @param {Blob} file 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async uploadFileToS3Form(file: Blob, options?: AxiosRequestConfig): Promise<AxiosResponse<string>> {
            return FileProccesorApiFp(configuration).uploadFileToS3Form(file, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * FileProccesorApi - object-oriented interface
 * @export
 * @class FileProccesorApi
 * @extends {BaseAPI}
 */
export class FileProccesorApi extends BaseAPI {
    /**
     * 
     * @summary Delete file from S3
     * @param {DeleteFileDto} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FileProccesorApi
     */
    public async deleteFileFromS3(body: DeleteFileDto, options?: AxiosRequestConfig) : Promise<AxiosResponse<boolean>> {
        return FileProccesorApiFp(this.configuration).deleteFileFromS3(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Delete many files from S3
     * @param {DeleteManyFilesDto} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FileProccesorApi
     */
    public async deleteManyFilesFromS3(body: DeleteManyFilesDto, options?: AxiosRequestConfig) : Promise<AxiosResponse<boolean>> {
        return FileProccesorApiFp(this.configuration).deleteManyFilesFromS3(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Upload file to S3
     * @param {Blob} file 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FileProccesorApi
     */
    public async uploadFileToS3Form(file: Blob, options?: AxiosRequestConfig) : Promise<AxiosResponse<string>> {
        return FileProccesorApiFp(this.configuration).uploadFileToS3Form(file, options).then((request) => request(this.axios, this.basePath));
    }
}
