/* tslint:disable */
/* eslint-disable */
/**
 * Hey Pharamcist API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Appointment
 */
export interface Appointment {
  _id?: string;
    /**
     * 
     * @type {Date}
     * @memberof Appointment
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Appointment
     */
    updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof Appointment
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Appointment
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof Appointment
     */
    event: string;
    /**
     * 
     * @type {string}
     * @memberof Appointment
     */
    storeId: string;
    /**
     * 
     * @type {string}
     * @memberof Appointment
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof Appointment
     */
    timeSlot: string;
    /**
     * 
     * @type {string}
     * @memberof Appointment
     */
    date: string;
}
