/* tslint:disable */
/* eslint-disable */
/**
 * Hey Pharamcist API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CampaignDraftSendingDto } from './campaign-draft-sending-dto';
/**
 * 
 * @export
 * @interface CampaignDraftSendingResponseDTO
 */
export interface CampaignDraftSendingResponseDTO {
  _id?: string;
    /**
     * 
     * @type {number}
     * @memberof CampaignDraftSendingResponseDTO
     */
    count: number;
    /**
     * 
     * @type {Array<CampaignDraftSendingDto>}
     * @memberof CampaignDraftSendingResponseDTO
     */
    data: Array<CampaignDraftSendingDto>;
    /**
     * 
     * @type {number}
     * @memberof CampaignDraftSendingResponseDTO
     */
    total: number;
}
