/* tslint:disable */
/* eslint-disable */
/**
 * Hey Pharamcist API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MarketingCampaignContentDTO } from './marketing-campaign-content-dto';
/**
 * 
 * @export
 * @interface CampaignContentResponseDTO
 */
export interface CampaignContentResponseDTO {
  _id?: string;
    /**
     * 
     * @type {number}
     * @memberof CampaignContentResponseDTO
     */
    count: number;
    /**
     * 
     * @type {Array<MarketingCampaignContentDTO>}
     * @memberof CampaignContentResponseDTO
     */
    data: Array<MarketingCampaignContentDTO>;
    /**
     * 
     * @type {number}
     * @memberof CampaignContentResponseDTO
     */
    total: number;
}
