/* tslint:disable */
/* eslint-disable */
/**
 * Hey Pharamcist API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CartItemPopulated } from './cart-item-populated';
import { ManualDiscount } from './manual-discount';
/**
 * 
 * @export
 * @interface CartBodyPopulated
 */
export interface CartBodyPopulated {
  _id?: string;
    /**
     * 
     * @type {Array<CartItemPopulated>}
     * @memberof CartBodyPopulated
     */
    items: Array<CartItemPopulated>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CartBodyPopulated
     */
    discountsApplied: Array<string>;
    /**
     * 
     * @type {ManualDiscount}
     * @memberof CartBodyPopulated
     */
    manualDiscount: ManualDiscount;
    /**
     * 
     * @type {Array<string>}
     * @memberof CartBodyPopulated
     */
    customProducts: Array<string>;
}
