/* tslint:disable */
/* eslint-disable */
/**
 * Hey Pharamcist API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProductVariant } from './product-variant';
/**
 * 
 * @export
 * @interface CartItemPopulated
 */
export interface CartItemPopulated {
  id?: string;
  _id?: string;
    /**
     * Product variant id
     * @type {string}
     * @memberof CartItemPopulated
     */
    productVariantId: string;
    /**
     * 
     * @type {number}
     * @memberof CartItemPopulated
     */
    quantity: number;
    /**
     * 
     * @type {ProductVariant}
     * @memberof CartItemPopulated
     */
    productVariantData: ProductVariant;
}
