/* tslint:disable */
/* eslint-disable */
/**
 * Hey Pharamcist API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CartItem
 */
export interface CartItem {
  _id?: string;
    /**
     * Product variant id
     * @type {string}
     * @memberof CartItem
     */
    productVariantId: string;
    /**
     * 
     * @type {number}
     * @memberof CartItem
     */
    quantity: number;
}
