/* tslint:disable */
/* eslint-disable */
/**
 * Hey Pharamcist API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CartItem } from './cart-item';
/**
 * 
 * @export
 * @interface CartBodyDTO
 */
export interface CartBodyDTO {
  _id?: string;
    /**
     * 
     * @type {Array<CartItem>}
     * @memberof CartBodyDTO
     */
    items: Array<CartItem>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CartBodyDTO
     */
    customProducts?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CartBodyDTO
     */
    discount?: string;
}
