/* tslint:disable */
/* eslint-disable */
/**
 * Hey Pharamcist API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PriceRange } from './price-range';
/**
 * 
 * @export
 * @interface CategoryFilters
 */
export interface CategoryFilters {
  _id?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CategoryFilters
     */
    brands: Array<string>;
    /**
     * 
     * @type {PriceRange}
     * @memberof CategoryFilters
     */
    priceRange: PriceRange;
    /**
     * 
     * @type {{ [key: string]: { [key: string]: number; }; }}
     * @memberof CategoryFilters
     */
    attributes: { [key: string]: { [key: string]: number; }; };
}
