/* tslint:disable */
/* eslint-disable */
/**
 * Hey Pharamcist API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ContactFullDTO } from './contact-full-dto';
/**
 * 
 * @export
 * @interface ContactFullResponseDTO
 */
export interface ContactFullResponseDTO {
  _id?: string;
    /**
     * 
     * @type {number}
     * @memberof ContactFullResponseDTO
     */
    count: number;
    /**
     * 
     * @type {Array<ContactFullDTO>}
     * @memberof ContactFullResponseDTO
     */
    data: Array<ContactFullDTO>;
    /**
     * 
     * @type {number}
     * @memberof ContactFullResponseDTO
     */
    total: number;
}
