/* tslint:disable */
/* eslint-disable */
/**
 * Hey Pharamcist API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ContactFullDTO
 */
export interface ContactFullDTO {
  _id?: string;
    /**
     * 
     * @type {string}
     * @memberof ContactFullDTO
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof ContactFullDTO
     */
    ID?: number;
    /**
     * 
     * @type {string}
     * @memberof ContactFullDTO
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof ContactFullDTO
     */
    unsubscribedAt: string;
    /**
     * 
     * @type {string}
     * @memberof ContactFullDTO
     */
    unsubscribedBy: string;
    /**
     * 
     * @type {string}
     * @memberof ContactFullDTO
     */
    lastActivityAt: string;
    /**
     * 
     * @type {string}
     * @memberof ContactFullDTO
     */
    lastUpdateAt: string;
    /**
     * 
     * @type {number}
     * @memberof ContactFullDTO
     */
    deliveredCount: number;
    /**
     * 
     * @type {boolean}
     * @memberof ContactFullDTO
     */
    isOptInPending: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ContactFullDTO
     */
    isSpamComplaining: boolean;
    /**
     * 
     * @type {string}
     * @memberof ContactFullDTO
     */
    exclusionFromCampaignsUpdatedAt: string;
    /**
     * 
     * @type {boolean}
     * @memberof ContactFullDTO
     */
    isExcludedFromCampaigns: boolean;
}
