/* tslint:disable */
/* eslint-disable */
/**
 * Hey Pharamcist API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SingleCountryStatsDto } from './single-country-stats-dto';
/**
 * 
 * @export
 * @interface CountryStatsResponseDTO
 */
export interface CountryStatsResponseDTO {
  _id?: string;
    /**
     * 
     * @type {number}
     * @memberof CountryStatsResponseDTO
     */
    count: number;
    /**
     * 
     * @type {Array<SingleCountryStatsDto>}
     * @memberof CountryStatsResponseDTO
     */
    data: Array<SingleCountryStatsDto>;
    /**
     * 
     * @type {number}
     * @memberof CountryStatsResponseDTO
     */
    total: number;
}
