/* tslint:disable */
/* eslint-disable */
/**
 * Hey Pharamcist API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CreateStoreAddressDto
 */
export interface CreateStoreAddressDto {
  _id?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateStoreAddressDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateStoreAddressDto
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateStoreAddressDto
     */
    company?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateStoreAddressDto
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateStoreAddressDto
     */
    street1?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateStoreAddressDto
     */
    street2?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateStoreAddressDto
     */
    street3?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateStoreAddressDto
     */
    streetNo?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateStoreAddressDto
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateStoreAddressDto
     */
    state?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateStoreAddressDto
     */
    zip?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateStoreAddressDto
     */
    country?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateStoreAddressDto
     */
    isDefault?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CreateStoreAddressDto
     */
    isResidential?: boolean;
    /**
     * 
     * @type {number}
     * @memberof CreateStoreAddressDto
     */
    latitude?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateStoreAddressDto
     */
    longitude?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateStoreAddressDto
     */
    addressType?: CreateStoreAddressDtoAddressTypeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum CreateStoreAddressDtoAddressTypeEnum {
    Billing = 'Billing',
    Shipping = 'Shipping',
    Both = 'Both'
}

