/* tslint:disable */
/* eslint-disable */
/**
 * Hey Pharamcist API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CreateUserGroupDto
 */
export interface CreateUserGroupDto {
  _id?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUserGroupDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUserGroupDto
     */
    description: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateUserGroupDto
     */
    users: Array<string>;
}
