/* tslint:disable */
/* eslint-disable */
/**
 * Hey Pharamcist API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CreateRoleDto
 */
export interface CreateRoleDto {
  _id?: string;
    /**
     * 
     * @type {Date}
     * @memberof CreateRoleDto
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CreateRoleDto
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof CreateRoleDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateRoleDto
     */
    description?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateRoleDto
     */
    canGetOrders?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CreateRoleDto
     */
    canGetProducts?: boolean;
}
