/* tslint:disable */
/* eslint-disable */
/**
 * Hey Pharamcist API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CreateInventoryLightDto } from './create-inventory-light-dto';
import { SingleProductMedia } from './single-product-media';
import { TableDto } from './table-dto';
/**
 * 
 * @export
 * @interface CreateSingleVariantProductDTO
 */
export interface CreateSingleVariantProductDTO {
  _id?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSingleVariantProductDTO
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSingleVariantProductDTO
     */
    description?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateSingleVariantProductDTO
     */
    tags: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CreateSingleVariantProductDTO
     */
    brand?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSingleVariantProductDTO
     */
    sku?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateSingleVariantProductDTO
     */
    showStock?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateSingleVariantProductDTO
     */
    reviews?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CreateSingleVariantProductDTO
     */
    upc?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSingleVariantProductDTO
     */
    modelNumber?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateSingleVariantProductDTO
     */
    parentSubCategories: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateSingleVariantProductDTO
     */
    parentCategories: Array<string>;
    /**
     * 
     * @type {Array<SingleProductMedia>}
     * @memberof CreateSingleVariantProductDTO
     */
    productMedia: Array<SingleProductMedia>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateSingleVariantProductDTO
     */
    frequentlyBoughtProducts: Array<string>;
    /**
     * The width of the product variant in cm
     * @type {number}
     * @memberof CreateSingleVariantProductDTO
     */
    width?: number;
    /**
     * The height of the product variant in cm
     * @type {number}
     * @memberof CreateSingleVariantProductDTO
     */
    height?: number;
    /**
     * The length of the product variant in cm
     * @type {number}
     * @memberof CreateSingleVariantProductDTO
     */
    length?: number;
    /**
     * The weight of the product variant in g
     * @type {number}
     * @memberof CreateSingleVariantProductDTO
     */
    weight?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateSingleVariantProductDTO
     */
    retailPrice?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateSingleVariantProductDTO
     */
    costPrice?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateSingleVariantProductDTO
     */
    totalSold?: number;
    /**
     * 
     * @type {Array<TableDto>}
     * @memberof CreateSingleVariantProductDTO
     */
    tables?: Array<TableDto>;
    /**
     * 
     * @type {Array<Blob>}
     * @memberof CreateSingleVariantProductDTO
     */
    media?: Array<Blob>;
    /**
     * 
     * @type {Array<CreateInventoryLightDto>}
     * @memberof CreateSingleVariantProductDTO
     */
    inventory?: Array<CreateInventoryLightDto>;
}
