/* tslint:disable */
/* eslint-disable */
/**
 * Hey Pharamcist API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UsedBy } from './used-by';
/**
 * 
 * @export
 * @interface Discount
 */
export interface Discount {
  _id?: string;
    /**
     * 
     * @type {Date}
     * @memberof Discount
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Discount
     */
    updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof Discount
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Discount
     */
    discountName: string;
    /**
     * 
     * @type {string}
     * @memberof Discount
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof Discount
     */
    discountType: DiscountDiscountTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof Discount
     */
    decreasePriceBy: DiscountDecreasePriceByEnum;
    /**
     * 
     * @type {string}
     * @memberof Discount
     */
    code: string;
    /**
     * 
     * @type {boolean}
     * @memberof Discount
     */
    automatic: boolean;
    /**
     * 
     * @type {number}
     * @memberof Discount
     */
    cappedAt: number;
    /**
     * 
     * @type {number}
     * @memberof Discount
     */
    amount: number;
    /**
     * 
     * @type {Date}
     * @memberof Discount
     */
    startsAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Discount
     */
    expiresAt: Date;
    /**
     * 
     * @type {number}
     * @memberof Discount
     */
    maxUses: number;
    /**
     * 
     * @type {number}
     * @memberof Discount
     */
    numberOfUses: number;
    /**
     * 
     * @type {string}
     * @memberof Discount
     */
    state: DiscountStateEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof Discount
     */
    categoriesEligible: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Discount
     */
    productsEligible: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Discount
     */
    variantsEligible: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Discount
     */
    storeId: string;
    /**
     * 
     * @type {Array<UsedBy>}
     * @memberof Discount
     */
    usedBy: Array<UsedBy>;
    /**
     * 
     * @type {number}
     * @memberof Discount
     */
    maxUsesPerUser: number;
    /**
     * 
     * @type {string}
     * @memberof Discount
     */
    minPurchaseRequired: DiscountMinPurchaseRequiredEnum;
    /**
     * 
     * @type {number}
     * @memberof Discount
     */
    minPurchaseAmount: number;
    /**
     * 
     * @type {number}
     * @memberof Discount
     */
    minPurchaseQuantity: number;
    /**
     * 
     * @type {string}
     * @memberof Discount
     */
    customerEligibility: DiscountCustomerEligibilityEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof Discount
     */
    usersEligible: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Discount
     */
    groupsEligible: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Discount
     */
    eligibleZipCodes: Array<string>;
}

/**
    * @export
    * @enum {string}
    */
export enum DiscountDiscountTypeEnum {
    CARTBALANCE = 'CART_BALANCE',
    SHIPPING = 'SHIPPING',
    PRODUCT = 'PRODUCT',
    CATEGORY = 'CATEGORY',
    VARIANT = 'VARIANT'
}
/**
    * @export
    * @enum {string}
    */
export enum DiscountDecreasePriceByEnum {
    PERCENTAGE = 'PERCENTAGE',
    AMOUNT = 'AMOUNT'
}
/**
    * @export
    * @enum {string}
    */
export enum DiscountStateEnum {
    ACTIVE = 'ACTIVE',
    INACTIVE = 'INACTIVE',
    EXPIRED = 'EXPIRED',
    SCHEDULED = 'SCHEDULED'
}
/**
    * @export
    * @enum {string}
    */
export enum DiscountMinPurchaseRequiredEnum {
    NOREQUIREMENT = 'NO_REQUIREMENT',
    MINIMUMAMOUNT = 'MINIMUM_AMOUNT',
    MINIMUMQUANTITY = 'MINIMUM_QUANTITY'
}
/**
    * @export
    * @enum {string}
    */
export enum DiscountCustomerEligibilityEnum {
    ALL = 'ALL',
    SPECIFICUSERS = 'SPECIFIC_USERS',
    SPECIFICGROUPS = 'SPECIFIC_GROUPS'
}

