/* tslint:disable */
/* eslint-disable */
/**
 * Hey Pharamcist API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PopulatedDiscount } from './populated-discount';
/**
 * 
 * @export
 * @interface DiscountPaginatedResponse
 */
export interface DiscountPaginatedResponse {
  _id?: string;
    /**
     * 
     * @type {Array<PopulatedDiscount>}
     * @memberof DiscountPaginatedResponse
     */
    data: Array<PopulatedDiscount>;
    /**
     * 
     * @type {number}
     * @memberof DiscountPaginatedResponse
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof DiscountPaginatedResponse
     */
    totalPages: number;
    /**
     * 
     * @type {number}
     * @memberof DiscountPaginatedResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof DiscountPaginatedResponse
     */
    limit: number;
}
