/* tslint:disable */
/* eslint-disable */
/**
 * Hey Pharamcist API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface EmailInvoiceDto
 */
export interface EmailInvoiceDto {
  _id?: string;
    /**
     * 
     * @type {string}
     * @memberof EmailInvoiceDto
     */
    to: string;
    /**
     * 
     * @type {string}
     * @memberof EmailInvoiceDto
     */
    subject: string;
    /**
     * 
     * @type {string}
     * @memberof EmailInvoiceDto
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof EmailInvoiceDto
     */
    orderId: string;
}
