/* tslint:disable */
/* eslint-disable */
/**
 * Hey Pharamcist API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ShallowParentCategoryDto } from './shallow-parent-category-dto';
import { SingleProductMedia } from './single-product-media';
/**
 * 
 * @export
 * @interface FrequentlyBoughtProductDto
 */
export interface FrequentlyBoughtProductDto {
  _id?: string;
    /**
     * 
     * @type {string}
     * @memberof FrequentlyBoughtProductDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof FrequentlyBoughtProductDto
     */
    name: string;
    /**
     * 
     * @type {Array<SingleProductMedia>}
     * @memberof FrequentlyBoughtProductDto
     */
    productMedia: Array<SingleProductMedia>;
    /**
     * 
     * @type {boolean}
     * @memberof FrequentlyBoughtProductDto
     */
    isDiscounted: boolean;
    /**
     * 
     * @type {number}
     * @memberof FrequentlyBoughtProductDto
     */
    discountAmount: number;
    /**
     * 
     * @type {number}
     * @memberof FrequentlyBoughtProductDto
     */
    retailPrice: number;
    /**
     * 
     * @type {number}
     * @memberof FrequentlyBoughtProductDto
     */
    finalPrice: number;
    /**
     * 
     * @type {ShallowParentCategoryDto}
     * @memberof FrequentlyBoughtProductDto
     */
    parentCategory: ShallowParentCategoryDto;
}
