/* tslint:disable */
/* eslint-disable */
/**
 * Hey Pharamcist API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SingleGeneralStats } from './single-general-stats';
/**
 * 
 * @export
 * @interface GeneralStatsResponseDTO
 */
export interface GeneralStatsResponseDTO {
  _id?: string;
    /**
     * 
     * @type {number}
     * @memberof GeneralStatsResponseDTO
     */
    count: number;
    /**
     * 
     * @type {Array<SingleGeneralStats>}
     * @memberof GeneralStatsResponseDTO
     */
    data: Array<SingleGeneralStats>;
    /**
     * 
     * @type {number}
     * @memberof GeneralStatsResponseDTO
     */
    total: number;
}
