/* tslint:disable */
/* eslint-disable */
/**
 * Hey Pharamcist API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GroupWithNoUsersDto
 */
export interface GroupWithNoUsersDto {
  _id?: string;
    /**
     * 
     * @type {Date}
     * @memberof GroupWithNoUsersDto
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof GroupWithNoUsersDto
     */
    updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof GroupWithNoUsersDto
     */
    id: string;
    /**
     * Name of the user group
     * @type {string}
     * @memberof GroupWithNoUsersDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof GroupWithNoUsersDto
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof GroupWithNoUsersDto
     */
    storeId: string;
    /**
     * 
     * @type {number}
     * @memberof GroupWithNoUsersDto
     */
    mailJetListId: number;
    /**
     * 
     * @type {number}
     * @memberof GroupWithNoUsersDto
     */
    percentageOfUsers: number;
    /**
     * 
     * @type {number}
     * @memberof GroupWithNoUsersDto
     */
    usersCount: number;
}
