/* tslint:disable */
/* eslint-disable */
/**
 * Hey Pharamcist API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProductVariant } from './product-variant';
/**
 * 
 * @export
 * @interface InventoryPaginatedResponse
 */
export interface InventoryPaginatedResponse {
  _id?: string;
    /**
     * 
     * @type {string}
     * @memberof InventoryPaginatedResponse
     */
    storeId?: string;
    /**
     * 
     * @type {ProductVariant}
     * @memberof InventoryPaginatedResponse
     */
    variant?: ProductVariant;
    /**
     * 
     * @type {number}
     * @memberof InventoryPaginatedResponse
     */
    quantity?: number;
    /**
     * 
     * @type {string}
     * @memberof InventoryPaginatedResponse
     */
    status?: InventoryPaginatedResponseStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof InventoryPaginatedResponse
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof InventoryPaginatedResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof InventoryPaginatedResponse
     */
    limit: number;
}

/**
    * @export
    * @enum {string}
    */
export enum InventoryPaginatedResponseStatusEnum {
    INSTOCK = 'IN_STOCK',
    OUTOFSTOCK = 'OUT_OF_STOCK',
    LOWSTOCK = 'LOW_STOCK'
}

