/* tslint:disable */
/* eslint-disable */
/**
 * Hey Pharamcist API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ManualShippingDto
 */
export interface ManualShippingDto {
  _id?: string;
    /**
     * 
     * @type {number}
     * @memberof ManualShippingDto
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof ManualShippingDto
     */
    shippingTitle: string;
    /**
     * 
     * @type {boolean}
     * @memberof ManualShippingDto
     */
    isFreeShipping: boolean;
    /**
     * 
     * @type {string}
     * @memberof ManualShippingDto
     */
    userAddressId: string;
}
