/* tslint:disable */
/* eslint-disable */
/**
 * Hey Pharamcist API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CartItem } from './cart-item';
import { CustomProductDto } from './custom-product-dto';
import { ManualDiscount } from './manual-discount';
import { ManualShippingDto } from './manual-shipping-dto';
/**
 * 
 * @export
 * @interface ManualOrderDTO
 */
export interface ManualOrderDTO {
  _id?: string;
    /**
     * 
     * @type {Array<CartItem>}
     * @memberof ManualOrderDTO
     */
    items?: Array<CartItem>;
    /**
     * 
     * @type {string}
     * @memberof ManualOrderDTO
     */
    notes?: string;
    /**
     * 
     * @type {ManualDiscount}
     * @memberof ManualOrderDTO
     */
    manualDiscount: ManualDiscount;
    /**
     * 
     * @type {string}
     * @memberof ManualOrderDTO
     */
    discountId: string;
    /**
     * 
     * @type {ManualShippingDto}
     * @memberof ManualOrderDTO
     */
    manualShipping: ManualShippingDto;
    /**
     * 
     * @type {Date}
     * @memberof ManualOrderDTO
     */
    paymentDueDate: Date;
    /**
     * 
     * @type {boolean}
     * @memberof ManualOrderDTO
     */
    chargeTax: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof ManualOrderDTO
     */
    orderRemindingDates: Array<string>;
    /**
     * 
     * @type {Array<CustomProductDto>}
     * @memberof ManualOrderDTO
     */
    customProducts?: Array<CustomProductDto>;
    /**
     * 
     * @type {string}
     * @memberof ManualOrderDTO
     */
    paymentMethod: ManualOrderDTOPaymentMethodEnum;
    /**
     * 
     * @type {string}
     * @memberof ManualOrderDTO
     */
    orderStatus: ManualOrderDTOOrderStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ManualOrderDTO
     */
    paymentStatus?: ManualOrderDTOPaymentStatusEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum ManualOrderDTOPaymentMethodEnum {
    Cash = 'Cash',
    Credit = 'Credit',
    Card = 'Card'
}
/**
    * @export
    * @enum {string}
    */
export enum ManualOrderDTOOrderStatusEnum {
    Pending = 'Pending',
    PickingPacking = 'Picking & Packing',
    ReadyForPickup = 'Ready for Pickup',
    Delivered = 'Delivered',
    OutForDelivery = 'Out for Delivery',
    PickedUp = 'Picked Up',
    Fulfilled = 'Fulfilled',
    Unfulfilled = 'Unfulfilled',
    OnHold = 'On Hold',
    Cancelled = 'Cancelled',
    InFulfillment = 'In Fulfillment'
}
/**
    * @export
    * @enum {string}
    */
export enum ManualOrderDTOPaymentStatusEnum {
    Paid = 'Paid',
    Unpaid = 'Unpaid'
}

