/* tslint:disable */
/* eslint-disable */
/**
 * Hey Pharamcist API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Product } from './product';
/**
 * 
 * @export
 * @interface MyFavoriteListDTO
 */
export interface MyFavoriteListDTO {
  _id?: string;
    /**
     * 
     * @type {string}
     * @memberof MyFavoriteListDTO
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof MyFavoriteListDTO
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof MyFavoriteListDTO
     */
    updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof MyFavoriteListDTO
     */
    user: string;
    /**
     * 
     * @type {Array<Product>}
     * @memberof MyFavoriteListDTO
     */
    items: Array<Product>;
}
