/* tslint:disable */
/* eslint-disable */
/**
 * Hey Pharamcist API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Notification
 */
export interface Notification {
  _id?: string;
    /**
     * 
     * @type {Date}
     * @memberof Notification
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Notification
     */
    updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    notificationType: string;
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    notificationLink: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Notification
     */
    sentTo: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Notification
     */
    readBy: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Notification
     */
    clearedBy: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof Notification
     */
    isAdminNotification: boolean;
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    storeId: string;
}
