/* tslint:disable */
/* eslint-disable */
/**
 * Hey Pharamcist API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface OpenApi
 */
export interface OpenApi {
  _id?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenApi
     */
    text: string;
    /**
     * 
     * @type {string}
     * @memberof OpenApi
     */
    title: string;
}
