/* tslint:disable */
/* eslint-disable */
/**
 * Hey Pharamcist API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface OrdersInsightsDto
 */
export interface OrdersInsightsDto {
  _id?: string;
    /**
     * 
     * @type {number}
     * @memberof OrdersInsightsDto
     */
    totalOrders: number;
    /**
     * 
     * @type {number}
     * @memberof OrdersInsightsDto
     */
    totalPendingOrders: number;
    /**
     * 
     * @type {number}
     * @memberof OrdersInsightsDto
     */
    totalProcessingOrders: number;
    /**
     * 
     * @type {number}
     * @memberof OrdersInsightsDto
     */
    totalCompletedOrders: number;
    /**
     * 
     * @type {number}
     * @memberof OrdersInsightsDto
     */
    totalCancelledOrders: number;
    /**
     * 
     * @type {number}
     * @memberof OrdersInsightsDto
     */
    totalReadyForPickUpOrders: number;
    /**
     * 
     * @type {number}
     * @memberof OrdersInsightsDto
     */
    totalOutForDeliveryOrders: number;
    /**
     * 
     * @type {number}
     * @memberof OrdersInsightsDto
     */
    draftsCount: number;
}
