/* tslint:disable */
/* eslint-disable */
/**
 * Hey Pharamcist API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SingleMessagePopulated } from './single-message-populated';
import { User } from './user';
/**
 * 
 * @export
 * @interface PopulatedChatDto
 */
export interface PopulatedChatDto {
  _id?: string;
    /**
     * 
     * @type {string}
     * @memberof PopulatedChatDto
     */
    id: string;
    /**
     * 
     * @type {Array<User>}
     * @memberof PopulatedChatDto
     */
    participants: Array<User>;
    /**
     * 
     * @type {Array<SingleMessagePopulated>}
     * @memberof PopulatedChatDto
     */
    conversation: Array<SingleMessagePopulated>;
    /**
     * 
     * @type {User}
     * @memberof PopulatedChatDto
     */
    createdBy: User;
    /**
     * 
     * @type {boolean}
     * @memberof PopulatedChatDto
     */
    isArchived: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PopulatedChatDto
     */
    isClosed: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PopulatedChatDto
     */
    isDeleted: boolean;
    /**
     * 
     * @type {Date}
     * @memberof PopulatedChatDto
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof PopulatedChatDto
     */
    updatedAt: Date;
    /**
     * 
     * @type {SingleMessagePopulated}
     * @memberof PopulatedChatDto
     */
    lastMessage: SingleMessagePopulated;
    /**
     * 
     * @type {number}
     * @memberof PopulatedChatDto
     */
    unreadMessages: number;
    /**
     * 
     * @type {boolean}
     * @memberof PopulatedChatDto
     */
    hasUnreadMessages: boolean;
}
