/* tslint:disable */
/* eslint-disable */
/**
 * Hey Pharamcist API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface RateDto
 */
export interface RateDto {
  _id?: string;
    /**
     * 
     * @type {string}
     * @memberof RateDto
     */
    amount: string;
    /**
     * 
     * @type {string}
     * @memberof RateDto
     */
    amountLocal: string;
    /**
     * 
     * @type {string}
     * @memberof RateDto
     */
    currency: string;
    /**
     * 
     * @type {string}
     * @memberof RateDto
     */
    currencyLocal: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof RateDto
     */
    attributes: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof RateDto
     */
    carrierAccount: string;
    /**
     * 
     * @type {string}
     * @memberof RateDto
     */
    durationTerms: string;
    /**
     * 
     * @type {number}
     * @memberof RateDto
     */
    estimatedDays: number;
    /**
     * 
     * @type {Date}
     * @memberof RateDto
     */
    objectCreated: Date;
    /**
     * 
     * @type {string}
     * @memberof RateDto
     */
    objectId: string;
    /**
     * 
     * @type {string}
     * @memberof RateDto
     */
    objectOwner: string;
    /**
     * 
     * @type {string}
     * @memberof RateDto
     */
    provider: string;
    /**
     * 
     * @type {string}
     * @memberof RateDto
     */
    providerImage75: string;
    /**
     * 
     * @type {string}
     * @memberof RateDto
     */
    providerImage200: string;
    /**
     * 
     * @type {string}
     * @memberof RateDto
     */
    shipment: string;
    /**
     * 
     * @type {boolean}
     * @memberof RateDto
     */
    test: boolean;
    /**
     * 
     * @type {any}
     * @memberof RateDto
     */
    servicelevel: any;
}
