/* tslint:disable */
/* eslint-disable */
/**
 * Hey Pharamcist API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface RefillRequest
 */
export interface RefillRequest {
  _id?: string;
    /**
     * 
     * @type {Date}
     * @memberof RefillRequest
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof RefillRequest
     */
    updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof RefillRequest
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof RefillRequest
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof RefillRequest
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof RefillRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof RefillRequest
     */
    phone: string;
    /**
     * 
     * @type {boolean}
     * @memberof RefillRequest
     */
    autoRefill: boolean;
    /**
     * 
     * @type {string}
     * @memberof RefillRequest
     */
    pickupOrDelivery: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof RefillRequest
     */
    rxNumbers: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof RefillRequest
     */
    storeId: string;
    /**
     * 
     * @type {string}
     * @memberof RefillRequest
     */
    notes: string;
    /**
     * 
     * @type {string}
     * @memberof RefillRequest
     */
    adminNotes: string;
    /**
     * 
     * @type {string}
     * @memberof RefillRequest
     */
    status: string;
}
