/* tslint:disable */
/* eslint-disable */
/**
 * Hey Pharamcist API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';
import { Order } from './order';
import { RateDto } from './rate-dto';
import { ShipmentDetailsDto } from './shipment-details-dto';
import { ShipmentStatusDto } from './shipment-status-dto';
import { TrackDto } from './track-dto';
/**
 * 
 * @export
 * @interface ShipmentWithOrder
 */
export interface ShipmentWithOrder {
  _id?: string;
    /**
     * 
     * @type {Date}
     * @memberof ShipmentWithOrder
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ShipmentWithOrder
     */
    updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof ShipmentWithOrder
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ShipmentWithOrder
     */
    user: string;
    /**
     * 
     * @type {string}
     * @memberof ShipmentWithOrder
     */
    storeId: string;
    /**
     * 
     * @type {string}
     * @memberof ShipmentWithOrder
     */
    transactionId: string;
    /**
     * 
     * @type {ShipmentDetailsDto}
     * @memberof ShipmentWithOrder
     */
    shipmentDetails: ShipmentDetailsDto;
    /**
     * 
     * @type {RateDto}
     * @memberof ShipmentWithOrder
     */
    rate: RateDto;
    /**
     * 
     * @type {ShipmentStatusDto}
     * @memberof ShipmentWithOrder
     */
    shipmentStatus: ShipmentStatusDto;
    /**
     * 
     * @type {TrackDto}
     * @memberof ShipmentWithOrder
     */
    trackingStatus: TrackDto;
    /**
     * 
     * @type {number}
     * @memberof ShipmentWithOrder
     */
    totalWeight: number;
    /**
     * 
     * @type {Address}
     * @memberof ShipmentWithOrder
     */
    inventoryAddress: Address;
    /**
     * 
     * @type {Order}
     * @memberof ShipmentWithOrder
     */
    order: Order;
}
