/* tslint:disable */
/* eslint-disable */
/**
 * Hey Pharamcist API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ShipmentStatusDto
 */
export interface ShipmentStatusDto {
  _id?: string;
    /**
     * 
     * @type {any}
     * @memberof ShipmentStatusDto
     */
    createdBy: any;
    /**
     * 
     * @type {string}
     * @memberof ShipmentStatusDto
     */
    labelUrl: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ShipmentStatusDto
     */
    messages: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ShipmentStatusDto
     */
    metadata: string;
    /**
     * 
     * @type {Date}
     * @memberof ShipmentStatusDto
     */
    objectCreated: Date;
    /**
     * 
     * @type {string}
     * @memberof ShipmentStatusDto
     */
    objectId: string;
    /**
     * 
     * @type {string}
     * @memberof ShipmentStatusDto
     */
    objectOwner: string;
    /**
     * 
     * @type {string}
     * @memberof ShipmentStatusDto
     */
    objectState: string;
    /**
     * 
     * @type {Date}
     * @memberof ShipmentStatusDto
     */
    objectUpdated: Date;
    /**
     * 
     * @type {string}
     * @memberof ShipmentStatusDto
     */
    parcel: string;
    /**
     * 
     * @type {string}
     * @memberof ShipmentStatusDto
     */
    rate: string;
    /**
     * 
     * @type {string}
     * @memberof ShipmentStatusDto
     */
    status: string;
    /**
     * 
     * @type {boolean}
     * @memberof ShipmentStatusDto
     */
    test: boolean;
    /**
     * 
     * @type {string}
     * @memberof ShipmentStatusDto
     */
    trackingNumber: string;
    /**
     * 
     * @type {string}
     * @memberof ShipmentStatusDto
     */
    trackingStatus: string;
    /**
     * 
     * @type {string}
     * @memberof ShipmentStatusDto
     */
    trackingUrlProvider: string;
}
