/* tslint:disable */
/* eslint-disable */
/**
 * Hey Pharamcist API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SingleBrowserStatsDto
 */
export interface SingleBrowserStatsDto {
  _id?: string;
    /**
     * 
     * @type {number}
     * @memberof SingleBrowserStatsDto
     */
    count: number;
    /**
     * 
     * @type {number}
     * @memberof SingleBrowserStatsDto
     */
    distinctCount: number;
    /**
     * 
     * @type {string}
     * @memberof SingleBrowserStatsDto
     */
    platform: string;
    /**
     * 
     * @type {string}
     * @memberof SingleBrowserStatsDto
     */
    userAgent: string;
}
