/* tslint:disable */
/* eslint-disable */
/**
 * Hey Pharamcist API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SingleContactAggregatedStatsDto
 */
export interface SingleContactAggregatedStatsDto {
  _id?: string;
    /**
     * 
     * @type {number}
     * @memberof SingleContactAggregatedStatsDto
     */
    blockedCount?: number;
    /**
     * 
     * @type {number}
     * @memberof SingleContactAggregatedStatsDto
     */
    bouncedCount?: number;
    /**
     * 
     * @type {number}
     * @memberof SingleContactAggregatedStatsDto
     */
    clickedCount?: number;
    /**
     * 
     * @type {number}
     * @memberof SingleContactAggregatedStatsDto
     */
    deferredCount?: number;
    /**
     * 
     * @type {number}
     * @memberof SingleContactAggregatedStatsDto
     */
    deliveredCount?: number;
    /**
     * 
     * @type {number}
     * @memberof SingleContactAggregatedStatsDto
     */
    hardBouncedCount?: number;
    /**
     * 
     * @type {string}
     * @memberof SingleContactAggregatedStatsDto
     */
    lastActivityAt?: string;
    /**
     * 
     * @type {number}
     * @memberof SingleContactAggregatedStatsDto
     */
    openedCount?: number;
    /**
     * 
     * @type {number}
     * @memberof SingleContactAggregatedStatsDto
     */
    preQueuedCount?: number;
    /**
     * 
     * @type {number}
     * @memberof SingleContactAggregatedStatsDto
     */
    processedCount?: number;
    /**
     * 
     * @type {number}
     * @memberof SingleContactAggregatedStatsDto
     */
    queuedCount?: number;
    /**
     * 
     * @type {number}
     * @memberof SingleContactAggregatedStatsDto
     */
    softBouncedCount?: number;
    /**
     * 
     * @type {number}
     * @memberof SingleContactAggregatedStatsDto
     */
    spamComplaintCount?: number;
    /**
     * 
     * @type {number}
     * @memberof SingleContactAggregatedStatsDto
     */
    unsubscribedCount?: number;
    /**
     * 
     * @type {number}
     * @memberof SingleContactAggregatedStatsDto
     */
    workFlowExitedCount?: number;
    /**
     * 
     * @type {number}
     * @memberof SingleContactAggregatedStatsDto
     */
    contactID: number;
    /**
     * 
     * @type {number}
     * @memberof SingleContactAggregatedStatsDto
     */
    marketingContacts: number;
    /**
     * 
     * @type {number}
     * @memberof SingleContactAggregatedStatsDto
     */
    userMarketingContacts: number;
}
