/* tslint:disable */
/* eslint-disable */
/**
 * Hey Pharamcist API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SingleRecipientDTO
 */
export interface SingleRecipientDTO {
  _id?: string;
    /**
     * The email address to which the test email will be sent.
     * @type {string}
     * @memberof SingleRecipientDTO
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof SingleRecipientDTO
     */
    name: string;
}
