/* tslint:disable */
/* eslint-disable */
/**
 * Hey Pharamcist API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface StatisticDto
 */
export interface StatisticDto {
  _id?: string;
    /**
     * 
     * @type {number}
     * @memberof StatisticDto
     */
    quarterlyDifference: number;
    /**
     * 
     * @type {number}
     * @memberof StatisticDto
     */
    yearlyDifference: number;
    /**
     * 
     * @type {number}
     * @memberof StatisticDto
     */
    dailyDifference: number;
    /**
     * 
     * @type {number}
     * @memberof StatisticDto
     */
    weeklyDifference: number;
    /**
     * 
     * @type {number}
     * @memberof StatisticDto
     */
    monthlyDifference: number;
    /**
     * 
     * @type {number}
     * @memberof StatisticDto
     */
    totalShipments: number;
    /**
     * 
     * @type {number}
     * @memberof StatisticDto
     */
    totalPayments: number;
    /**
     * 
     * @type {number}
     * @memberof StatisticDto
     */
    totalQuotes: number;
    /**
     * 
     * @type {number}
     * @memberof StatisticDto
     */
    categoriesCount: number;
    /**
     * 
     * @type {number}
     * @memberof StatisticDto
     */
    subCategoriesCount: number;
    /**
     * 
     * @type {number}
     * @memberof StatisticDto
     */
    productsCount: number;
    /**
     * 
     * @type {number}
     * @memberof StatisticDto
     */
    totalUsersCount: number;
    /**
     * 
     * @type {number}
     * @memberof StatisticDto
     */
    usersRegisteredToday: number;
    /**
     * 
     * @type {number}
     * @memberof StatisticDto
     */
    usersRegisteredThisWeek: number;
    /**
     * 
     * @type {number}
     * @memberof StatisticDto
     */
    usersRegisteredThisMonth: number;
    /**
     * 
     * @type {number}
     * @memberof StatisticDto
     */
    usersRegisteredThisYear: number;
    /**
     * 
     * @type {number}
     * @memberof StatisticDto
     */
    totalOrders: number;
    /**
     * 
     * @type {number}
     * @memberof StatisticDto
     */
    ordersYTDCount: number;
    /**
     * 
     * @type {number}
     * @memberof StatisticDto
     */
    ordersYTDTotal: number;
    /**
     * 
     * @type {number}
     * @memberof StatisticDto
     */
    ordersMTDCount: number;
    /**
     * 
     * @type {number}
     * @memberof StatisticDto
     */
    ordersMTDTotal: number;
    /**
     * 
     * @type {number}
     * @memberof StatisticDto
     */
    ordersWTDCount: number;
    /**
     * 
     * @type {number}
     * @memberof StatisticDto
     */
    ordersWTDTotal: number;
    /**
     * 
     * @type {number}
     * @memberof StatisticDto
     */
    ordersQTDCount: number;
    /**
     * 
     * @type {number}
     * @memberof StatisticDto
     */
    ordersQTDTotal: number;
}
