/* tslint:disable */
/* eslint-disable */
/**
 * Hey Pharamcist API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Store
 */
export interface Store {
  _id?: string;
    /**
     * 
     * @type {Date}
     * @memberof Store
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Store
     */
    updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof Store
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Store
     */
    storeName: string;
    /**
     * 
     * @type {string}
     * @memberof Store
     */
    phoneNumber: string;
    /**
     * 
     * @type {string}
     * @memberof Store
     */
    email: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Store
     */
    storeAdmins: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Store
     */
    originUrl: string;
    /**
     * 
     * @type {string}
     * @memberof Store
     */
    adminUrl: string;
    /**
     * 
     * @type {string}
     * @memberof Store
     */
    shippingApi?: string;
    /**
     * 
     * @type {string}
     * @memberof Store
     */
    stripeApiKey: string;
    /**
     * 
     * @type {string}
     * @memberof Store
     */
    stripeWebhookSecret: string;
    /**
     * 
     * @type {string}
     * @memberof Store
     */
    googleAnalyticsViewId: string;
    /**
     * 
     * @type {string}
     * @memberof Store
     */
    twilioAccountSid: string;
    /**
     * 
     * @type {string}
     * @memberof Store
     */
    twilioAuthToken: string;
    /**
     * 
     * @type {string}
     * @memberof Store
     */
    twilioPhoneNumber: string;
    /**
     * ISO 4217 currency code
     * @type {string}
     * @memberof Store
     */
    storeCurrency: string;
    /**
     * 
     * @type {string}
     * @memberof Store
     */
    storeAddress: string;
    /**
     * 
     * @type {string}
     * @memberof Store
     */
    storeBillingAddress: string;
}
