/* tslint:disable */
/* eslint-disable */
/**
 * Hey Pharamcist API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FlatSubCategory } from './flat-sub-category';
/**
 * 
 * @export
 * @interface SubCategory
 */
export interface SubCategory {
  _id?: string;
    /**
     * 
     * @type {Date}
     * @memberof SubCategory
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof SubCategory
     */
    updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof SubCategory
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof SubCategory
     */
    parentCategory: string;
    /**
     * 
     * @type {string}
     * @memberof SubCategory
     */
    parentSubCategory: string;
    /**
     * 
     * @type {Array<FlatSubCategory>}
     * @memberof SubCategory
     */
    childSubCategories: Array<FlatSubCategory>;
    /**
     * 
     * @type {Array<string>}
     * @memberof SubCategory
     */
    subCategoryProducts: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof SubCategory
     */
    subCategoryVariants: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof SubCategory
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof SubCategory
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof SubCategory
     */
    image: string;
    /**
     * 
     * @type {boolean}
     * @memberof SubCategory
     */
    isActive: boolean;
    /**
     * 
     * @type {Date}
     * @memberof SubCategory
     */
    activeChangedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof SubCategory
     */
    storeId: string;
}
