/* tslint:disable */
/* eslint-disable */
/**
 * Hey Pharamcist API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UserEntity } from './user-entity';
/**
 * 
 * @export
 * @interface TUserSessionData
 */
export interface TUserSessionData {
  _id?: string;
    /**
     * 
     * @type {UserEntity}
     * @memberof TUserSessionData
     */
    userData: UserEntity;
    /**
     * 
     * @type {string}
     * @memberof TUserSessionData
     */
    authToken: string;
}
