/* tslint:disable */
/* eslint-disable */
/**
 * Hey Pharamcist API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UpdateTransferePatientsRequestDto
 */
export interface UpdateTransferePatientsRequestDto {
  _id?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTransferePatientsRequestDto
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTransferePatientsRequestDto
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTransferePatientsRequestDto
     */
    address?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTransferePatientsRequestDto
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTransferePatientsRequestDto
     */
    dob?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTransferePatientsRequestDto
     */
    prevPharmacyName?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTransferePatientsRequestDto
     */
    prevPharmacyPhone?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateTransferePatientsRequestDto
     */
    transferAll?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateTransferePatientsRequestDto
     */
    rxNumbers?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateTransferePatientsRequestDto
     */
    specificScripts?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof UpdateTransferePatientsRequestDto
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTransferePatientsRequestDto
     */
    status?: string;

    /**
     * 
     * @type {string}
     * @memberof UpdateTransferePatientsRequestDto
     */
    adminNotes?: string;
}
