/* tslint:disable */
/* eslint-disable */
/**
 * Hey Pharamcist API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ZoneSingleSize } from './zone-single-size';
/**
 * 
 * @export
 * @interface UpdateZoneDto
 */
export interface UpdateZoneDto {
  _id?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateZoneDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateZoneDto
     */
    description?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateZoneDto
     */
    zipCodes?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof UpdateZoneDto
     */
    cost?: number;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateZoneDto
     */
    isFreeShipping?: boolean;
    /**
     * 
     * @type {number}
     * @memberof UpdateZoneDto
     */
    estimatedDeliveryTime?: number;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateZoneDto
     */
    active?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateZoneDto
     */
    deleted?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UpdateZoneDto
     */
    storeAddressId?: string;
    /**
     * 
     * @type {Array<ZoneSingleSize>}
     * @memberof UpdateZoneDto
     */
    sizes?: Array<ZoneSingleSize>;
}
