/* tslint:disable */
/* eslint-disable */
/**
 * Hey Pharamcist API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CreateInventoryLightDto } from './create-inventory-light-dto';
import { TableDto } from './table-dto';
/**
 * 
 * @export
 * @interface UpdateProductVariantDto
 */
export interface UpdateProductVariantDto {
  _id?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProductVariantDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProductVariantDto
     */
    description?: string;
    /**
     * The width of the product variant in cm
     * @type {number}
     * @memberof UpdateProductVariantDto
     */
    width?: number;
    /**
     * The height of the product variant in cm
     * @type {number}
     * @memberof UpdateProductVariantDto
     */
    height?: number;
    /**
     * The length of the product variant in cm
     * @type {number}
     * @memberof UpdateProductVariantDto
     */
    length?: number;
    /**
     * The weight of the product variant in g
     * @type {number}
     * @memberof UpdateProductVariantDto
     */
    weight?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateProductVariantDto
     */
    brand?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProductVariantDto
     */
    sku?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof UpdateProductVariantDto
     */
    attribute?: { [key: string]: string; };
    /**
     * 
     * @type {number}
     * @memberof UpdateProductVariantDto
     */
    retailPrice?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateProductVariantDto
     */
    costPrice?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateProductVariantDto
     */
    totalSold?: number;
    /**
     * 
     * @type {Array<TableDto>}
     * @memberof UpdateProductVariantDto
     */
    tables?: Array<TableDto>;
    /**
     * 
     * @type {Array<Blob>}
     * @memberof UpdateProductVariantDto
     */
    media?: Array<Blob>;
    /**
     * 
     * @type {Array<CreateInventoryLightDto>}
     * @memberof UpdateProductVariantDto
     */
    inventory?: Array<CreateInventoryLightDto>;
}
