/* tslint:disable */
/* eslint-disable */
/**
 * Hey Pharamcist API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface User
 */
export interface User {
  _id?: string;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    firstname: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    lastname: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    password: string;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    isEmailVerified: boolean;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    role: UserRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    avatar: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    phoneNumber: string;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    lastActive: Date;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    notes: string;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    mailJetId: number;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    storeId: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    customerType: UserCustomerTypeEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof User
     */
    adminStores: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    isEmailNotifActive: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    isSmsNotifActive: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    alertOnUserRegistration: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    alertOnOrderCreation: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    alertOnOrderDelivery: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    alertOnNewReview: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    isActive: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    isBlocked: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    isTaxExempted: boolean;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    stripeCustomerId: string;
    /**
     * ISO 3166-1 alpha-2 country code ... examples -> https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
     * @type {string}
     * @memberof User
     */
    country: string;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    availableCreditBalance: number;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    creditLimit: number;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    creditUsed: number;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    isAllowedtToUseCredit: boolean;
}

/**
    * @export
    * @enum {string}
    */
export enum UserRoleEnum {
    SuperAdmin = 'SuperAdmin',
    Admin = 'Admin',
    User = 'User'
}
/**
    * @export
    * @enum {string}
    */
export enum UserCustomerTypeEnum {
    B2B = 'B2B',
    Regular = 'Regular'
}

