/* tslint:disable */
/* eslint-disable */
/**
 * Hey Pharamcist API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface VerifyEmailDTO
 */
export interface VerifyEmailDTO {
  _id?: string;
    /**
     * 
     * @type {string}
     * @memberof VerifyEmailDTO
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof VerifyEmailDTO
     */
    token: string;
}
